- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - key.yml
 
  vars_prompt:
  - name: MACHINE_NAME
    prompt: "Please Enter machine name: "
    private: no
    when: MACHINE_NAME is undefined 
 
  - name: REGION
    prompt: "Enter Region of this instance: "
    private: no
    when: REGION is undefined

  - name: SUBNET_ID
    prompt: "Enter SUBNET ID for this instance: "
    private: no
    when: SUBNET_ID is undefined

  - name: AMI
    prompt: "Enter ami of the instance: "
    private: no
    when: AMI is undefine

  - name: INSTANCE_TYPE
    prompt: "Instance type (ex: t1.micro, c1.large, etc): "
    private: no
    when: INSTANCE_TYPE is undefined

  tasks:
  #- name: adding key to 
  #  ec2_key: 
  #    name: hoa_ly3
  #    key_material: "{{ item }}"
  #    region: us-west-2
  #  with_file: ~/.ssh/id_rsa.pub
  - name: create an EC2 instance
    ec2:
      aws_access_key: "{{ AWS_ACCESS_KEY }}"
      aws_secret_key: "{{ AWS_SECRECT_KEY }}"
      key_name: "{{ KEY }}"
      region: "{{ REGION }}"
      instance_tags: { "Name":"example" }
      instance_type: "{{ INSTANCE_TYPE }}"
      image: "{{ AMI }}"
      vpc_subnet_id: "{{ SUBNET_ID }}"
      wait: yes
      count: 1
    register: ec2

  - debug: var=item
    with_items: ec2.instances
  
  - name: add the instance to web and production groups
    local_action: add_host hostname={{ item.public_dns_name }}
                  groupname=production
                  ansible_ssh_user=ubuntu
    with_items: ec2.instances

  - name: Wait for the instances to boot by checking the ssh port
    wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances

