- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Create security group
    ec2_group:
      name: launch-wizard-8
      description: "A Security group"
      region: us-west-2
      rules:
        - proto: tcp
          type: ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          type: all
          cidr_ip: 0.0.0.0/0
    register: ec2_firewall

  - name: create an EC2 instance
    ec2:
      key_name: hoa_ly
      region: us-west-2
      group_id: "{{ec2_firewall..group_id}}"
      instance_type: t2.micro
      image: ami-63b25203
      instance_tags: '{"Name": "example"}'
      wait: yes
    register: ec2

  - debug: var=item
    with_items: ec2.instances

  - name: Wait for the instances to boot by checking the ssh port
    wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
    with_items: ec2.instances
