---
# tasks file for roles/Jenkins
- name: Demo 
  command: mkdir {{ inventory_hostname }}

- name: Install python software probperties
  apt: name=python-software-properties state=installed update_cache=yes cache_valid_time=86400

- name: Install necessary things such as git, java, python and apache
  apt: name={{ item }} state=installed
  with_items:
  - 'python-pycurl'
  - 'openjdk-7-jre'
  - 'openjdk-7-jdk'
  - 'git'
  - 'curl'
  - 'apache2'

- name: Add Jenkine keys 
  apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: Add Jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present update_cache=yes

- name: Install Jenkins
  apt: name=jenkins update_cache=yes force=yes state=latest
  register: jenkins_instal

- name: Enable Apache proxy
  sudo: yes
  command: a2enmod proxy

- name: Enable Apache proxy http
  sudo: yes
  command: a2enmod proxy_http

- name: Configuration of jenkins.conf
  sudo: yes
  template: src=jenkins.conf.j2 dest=/etc/apache2/sites-available/jenkins.conf

- name: Enable Jenkins
  sudo: yes 
  command: a2ensite jenkins

- name: Reload Apache
  sudo: yes
  service: name=apache2 state=reloaded
